name: UPDATE

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        if: ${{ env.FILES != '' }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        if: ${{ env.FILES != '' }}
        run: python -m pip install poetry
      - name: Check unused imports
        run: poetry update
        timeout-minutes: 5
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1
